name: cd

on:
  workflow_dispatch:
  push:
    tags:
      - v-*

env:
  CLOUDFORMATION_STACK_NAME: ${{ secrets.PROJECT_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Provision
        run: aws cloudformation deploy --stack-name ${{ env.CLOUDFORMATION_STACK_NAME }} --template ./template.yml --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --no-cli-pager
